FROM python:3.12

WORKDIR /code

RUN apt-get update && \
    apt-get install -y \
    gdal-bin \
    libgdal-dev \
    python3-gdal \
    libgeos-dev \
    libproj-dev \
    g++ \
    make \
    wget \
    libfontconfig \
    libxrender1 \
    libjpeg-dev \
    xfonts-base && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


COPY ./ /code
RUN --mount=type=cache,target=/root/.cache/pip python3 -m pip install -r requirements.txt

CMD ["sh", "./resources/scripts/entrypoint.sh"]